name: flybase-metadata-update
on:
  push:
    branches: ["flybase-gh-actions"]
  workflow_dispatch:
jobs:
  update-flybase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install

