name: flybase-metadata-update
on:
  workflow_dispatch:
jobs:
  update-flybase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          cache: 'poetry'
      - run: poetry install

